refactor(rector): auto-fixed issues

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -18,6 +18,22 @@ if [[ $? -ne 0 ]]; then
     exit 1
 fi
 
+echo -e "\n"
+echo -e "\033[1mRunning Rector (dry-run)...\033[0m"
+echo ""
+
+composer run-script rector
+if [[ $? -ne 0 ]]; then
+    echo "Rector found issues. Run 'composer rector:fix' to apply changes. Commit aborted."
+    echo -e "\n"
+
+    # show current file path
+    echo -e "\033[1mPre-commit checks were executed by ${current_full_path}.\033[0m"
+    echo -e "\n"
+
+    exit 1
+fi
+
 # show current file path
 echo -e "\033[1mPre-commit checks were executed by ${current_full_path}.\033[0m"
 echo -e "\n"
